# Generated by Django 4.1.2 on 2022-10-28 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_auther_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 2, 48, 20, 257713, tzinfo=datetime.timezone.utc)),
        ),
    ]
